### ISSUE TITLE
chrome support on windows

### ISSUE THREAD

**Issue by k1nghat** [n8henrie/pycookiecheat#13]
i found this and seems to work on windows for chrome decryption: https://gist.github.com/DakuTree/428e5b737306937628f2944fbfdc4ffc

**Comment by n8henrie** [comment]
Thanks for the link. What is the installation process for win32crypt? Will a simple `pip install` or `python setup.py` work?

**Comment by madLyfe** [comment]
need to install pypiwin32 package and import win32crypt is all.

**Comment by n8henrie** [comment]
Well, as [I've said in the FAQ](https://github.com/n8henrie/pycookiecheat#how-about-windows), I don't think I'll be able to work on (or maintain code related to) this issue due to lack of a PC, so I'm going to go ahead and close for now. Anybody that is interested is free to make a PR and I'll re-open -- doesn't look like it would be too hard. Thanks again for pointing out some example code.

**Comment by Chaaang** [comment]
I'm curious about a VMware Fusion is hard to install? or just virtual box and simple install a low memory win7?

**Comment by n8henrie** [comment]
@Chaaang I have no problem getting a virtualized Windows system up and running, but I haven't a clue how to set up a Windows dev environment, and to be honest I'm not interested in learning just for the sake of this project. Maintaining it for Windows going forward sounds completely unappealing. As I've said, feel free to open a pull request.

**Comment by n8henrie** [comment]
Nice. Can you make a few automated tests for Windows and then a pull request so we can make sure all the tests are still passing? I am not enthusiastic about maintaining code for an OS that I don't have, so incorporating automated tests will be critical.

Also, I'm not exactly sure about line 251 -- can you walk me through what this is doing? I don't even see a variable named `value`, am I missing it?

**Comment by n8henrie** [comment]
Bump.

This issue is pending a response and is blocked until I have more info. To keep the issue list groomed, I will often close these stalled issues if they go a prolonged time without a response. In this case, I will give it another week or so.

**Comment by n8henrie** [comment]
I haven't gotten a reply, so I'm closing this issue as dead. Please feel free to let me know if I should re-open.
