### ISSUE TITLE
Error while using lib

### ISSUE THREAD

**Issue by ikelca** [n8henrie/pycookiecheat#16]
I ran the same code 

from pycookiecheat import chrome_cookies
import requests

url = 'http://example.com/fake.html'
cookies = chrome_cookies(url)
r = requests.get(url, cookies=cookies)  

and keep getting following error, any idea? 

File "/Users/kelvin/anaconda/envs/gl-env/lib/python2.7/site-packages/pycookiecheat/pycookiecheat.py", line 27
    def clean(decrypted: bytes) -> str:
                       ^
SyntaxError: invalid syntax

**Comment by joingh123** [comment]
use v0.3.5 and try again
`pip install pycookiecheat==0.3.5`

**Comment by n8henrie** [comment]
Agreed, looks like you're using the wrong version of python:

> File "/Users/kelvin/anaconda/envs/gl-env/lib/python2.7/site-

From [the installation section of the readme](https://github.com/n8henrie/pycookiecheat#installation): 

> NB: Use pip and python instead of pip3 and python3 if you're still on Python 2 and using pycookiecheat < v0.4.0. pycookiecheat >= v0.4.0 requires Python 3.5+, and may soon go to 3.6+.

If you can, I highly recommend upgrading to Python 3.6.
