### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by Chaaang** [n8henrie/pycookiecheat#19]
simple ask a question. The cookie will be writed back by chrome whenever the value of cookie changed ? Or just when I close chrome.

**Comment by n8henrie** [comment]
It seems to vary. Definitely when you close Chrome, but often (not always) seems to be written to file even before closing.

**Comment by Chaaang** [comment]
@n8henrie thanks， how about design a broswer extension, which sync browser cookies with mysql.....

**Comment by n8henrie** [comment]
Sounds like a cool idea, feel free to make a pull request.
