### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by HortonX25** [n8henrie/pycookiecheat#20]
I'm attempting to run this code

`
from pycookiecheat import chrome_cookies
import requests

url = 'https://www.google.com'

cookies = chrome_cookies(url)
r = requests.get(url, cookies=cookies)

`

Upon doing so, I get this error:

root@Computer:~/PycharmProjects/Test# python Test.py 
Traceback (most recent call last):
  File "Test.py", line 1, in <module>
    from pycookiecheat import chrome_cookies
  File "/usr/local/lib/python2.7/dist-packages/pycookiecheat/__init__.py", line 3, in <module>
    from pycookiecheat.pycookiecheat import chrome_cookies  # noqa
  File "/usr/local/lib/python2.7/dist-packages/pycookiecheat/pycookiecheat.py", line 27
    def clean(decrypted: bytes) -> str:
                       ^
SyntaxError: invalid syntax

**Comment by n8henrie** [comment]
From the [readme](https://github.com/n8henrie/pycookiecheat#installation):

> pycookiecheat >= v0.4.0 requires Python 3.5+, and may soon go to 3.6+.

Try installing a version < v0.4.0.
