### ISSUE TITLE
GLib.Error: g-io-error-quark problem

### ISSUE THREAD

**Issue by hieonn** [n8henrie/pycookiecheat#23]
Dear guys!

I've got a problem on using pycookiecheat in Ubuntu 16.04 LTS, python 2.7 environment. All installation  seem to be successful but got a problem when using the pycookiecheat (version 0.3.5). The error message is "GLib.Error: g-io-error-quark: Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached (24)," so that I've tried to resolve the issue but never have any luck. 

Please, give me any clue to resolve it. Thanks for advance!

**Comment by n8henrie** [comment]
Thanks for including the version info.

I know nothing about that library; it seems likely that the error that you're experiencing is something you'd need to address with them, and not with pycookiecheat.

To be sure, I'll need a fair amount more info, like the stack trace and what command you're running to provoke the error.

I'll leave this issue open for a week or so to see if any others want to chime in and help, but after that I'll likely close it unless there is new information that leads me to believe this is an issue with pycookiecheat's code base.

**Comment by hieonn** [comment]
Hi! n8henrie!  

Thanks for your comment and your great work!. The lib seems to be related to Secret. The error message in pycheatcookie is like belows.

File "/usr/local/lib/python2.7/dist-packages/pycookiecheat/pycookiecheat.py", line 89, in chrome_cookies
    service = Secret.Service.get_sync(flags)
GLib.Error: g-io-error-quark: Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached (24)

I will dig into more and will let you know if I have resolution or more clues. Thanks!

**Comment by n8henrie** [comment]
If you can't run the code below, then I think the issue is something with your setup.

```python
import gi
gi.require_version('Secret', '1')
from gi.repository import Secret

flags = Secret.ServiceFlags.LOAD_COLLECTIONS
service = Secret.Service.get_sync(flags)
```

Reference: https://developer.gnome.org/libsecret/unstable/SecretService.html

**Comment by hieonn** [comment]
@n8henrie Great thanks for your clue and now I've resolved the problem I had committed.

First of all, I was trying to use the script over ssh so that gi service didn't work. so that I've made a setting statement for my own secret in my_pass variable with if clause by "if SSH_CONNECTION" in os.environ" getting secret information 

Secondly, In SSH environment, I needed to set cookie file path in full path form in order to use sqlite3 

Now, I can use your great script over SSH! Thanks!

**Comment by hieonn** [comment]
I've been trying to find how to use the service in ssh but failed. I will close the issue anyway and will add up any comment if I find other way to make it. Thanks!

**Comment by mahesh3097** [comment]
Hey @hieonn , I am facing the same issue right now. I am trying to run a flask application on a server and I am getting this error. Can you help me out with this as I am not able to fully understand what this error is and how to resolve it

**Comment by michaellee94** [comment]
I have a fix for this. You need to make sure `DISPLAY` and `DBUS_SESSION_BUS_ADDRESS` are set.

https://comeandtechit.wordpress.com/2018/11/26/glib-error-g-io-error-quark-cannot-autolaunch-d-bus-without-x11-display/
