### ISSUE TITLE
chrome_cookies(url) : UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 0: invalid start byte

### ISSUE THREAD

**Issue by munish259272** [n8henrie/pycookiecheat#27]
###Google Chrome : Version 73.0.3683.75 (Official Build) (64-bit)
### centos-release-7-6.1810.2.el7.centos.x86_64

This is how i installed it :
########################################################################
(base) [msingh@centos Python Epiphanies]$ pip install git+https://github.com/n8henrie/pycookiecheat.git
Collecting git+https://github.com/n8henrie/pycookiecheat.git
  Cloning https://github.com/n8henrie/pycookiecheat.git to /tmp/pip-req-build-ubqjkpwe
  Running command git clone -q https://github.com/n8henrie/pycookiecheat.git /tmp/pip-req-build-ubqjkpwe
Requirement already satisfied (use --upgrade to upgrade): pycookiecheat==0.4.4 from git+https://github.com/n8henrie/pycookiecheat.git in /home/msingh/anaconda3/lib/python3.7/site-packages
Requirement already satisfied: keyring==16.1.0 in /home/msingh/anaconda3/lib/python3.7/site-packages (from pycookiecheat==0.4.4) (16.1.0)
Requirement already satisfied: pycrypto==2.6.1 in /home/msingh/anaconda3/lib/python3.7/site-packages (from pycookiecheat==0.4.4) (2.6.1)
Requirement already satisfied: secretstorage; sys_platform == "linux" and python_version >= "3.5" in /home/msingh/anaconda3/lib/python3.7/site-packages (from keyring==16.1.0->pycookiecheat==0.4.4) (3.1.1)
Requirement already satisfied: entrypoints in /home/msingh/anaconda3/lib/python3.7/site-packages (from keyring==16.1.0->pycookiecheat==0.4.4) (0.3)
Requirement already satisfied: cryptography in /home/msingh/anaconda3/lib/python3.7/site-packages (from secretstorage; sys_platform == "linux" and python_version >= "3.5"->keyring==16.1.0->pycookiecheat==0.4.4) (2.6.1)
Requirement already satisfied: jeepney in /home/msingh/anaconda3/lib/python3.7/site-packages (from secretstorage; sys_platform == "linux" and python_version >= "3.5"->keyring==16.1.0->pycookiecheat==0.4.4) (0.4)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in /home/msingh/anaconda3/lib/python3.7/site-packages (from cryptography->secretstorage; sys_platform == "linux" and python_version >= "3.5"->keyring==16.1.0->pycookiecheat==0.4.4) (1.12.3)
Requirement already satisfied: six>=1.4.1 in /home/msingh/anaconda3/lib/python3.7/site-packages (from cryptography->secretstorage; sys_platform == "linux" and python_version >= "3.5"->keyring==16.1.0->pycookiecheat==0.4.4) (1.12.0)
Requirement already satisfied: asn1crypto>=0.21.0 in /home/msingh/anaconda3/lib/python3.7/site-packages (from cryptography->secretstorage; sys_platform == "linux" and python_version >= "3.5"->keyring==16.1.0->pycookiecheat==0.4.4) (0.24.0)
Requirement already satisfied: pycparser in /home/msingh/anaconda3/lib/python3.7/site-packages (from cffi!=1.11.3,>=1.8->cryptography->secretstorage; sys_platform == "linux" and python_version >= "3.5"->keyring==16.1.0->pycookiecheat==0.4.4) (2.19)
Building wheels for collected packages: pycookiecheat
  Building wheel for pycookiecheat (setup.py) ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-m3pfsn3n/wheels/ee/b4/70/b0c41074a262957218b1c878a034bc43292d3c8d5dbb121ca0
Successfully built pycookiecheat
###########################################################################

>>> from pycookiecheat import chrome_cookies
>>> import requests
>>> url='https://learning.oreilly.com/home/'
>>> cookies = chrome_cookies(url)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/msingh/anaconda3/lib/python3.7/site-packages/pycookiecheat/pycookiecheat.py", line 228, in chrome_cookies
    init_vector=config['init_vector'])
  File "/home/msingh/anaconda3/lib/python3.7/site-packages/pycookiecheat/pycookiecheat.py", line 63, in chrome_decrypt
    return clean(decrypted)
  File "/home/msingh/anaconda3/lib/python3.7/site-packages/pycookiecheat/pycookiecheat.py", line 40, in clean
    return decrypted[:-last].decode('utf8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 0: invalid start byte

**Comment by n8henrie** [comment]
These errors are tough to debug, since I can't reproduce them locally.

To even give it a shot, I'd need you to either post the bytes for `decrypted`.

Otherwise, you're welcome to jump in the debugger and try a few different codecs to see if you can find one that works.

**Comment by n8henrie** [comment]
Bump.

This issue is pending a response and is blocked until I have more info. To keep the issue list groomed, I will often close these stalled issues if they go a prolonged time without a response. In this case, I will give it another week or so.

**Comment by munish259272** [comment]
You can close this case.
I believe i was having problem with importing gi module

instead i  am using secret storage module now and it seems to work for my Linux machine.
I am not an expert in python but somehow it works now for me with little editing.

def get_linux_config(browser: str) -> dict:
    """Get the settings for Chrome/Chromium cookies on Linux.

    Args:
        browser: Either "Chrome" or "Chromium"
    Returns:
        Config dictionary for Chrome/Chromium cookie decryption

    """
    bus = secretstorage.dbus_init()
    collection = secretstorage.get_any_collection(bus)  ## login keyring
    # Verify supported browser, fail early otherwise
    if browser.lower() == "chrome":
        cookie_file = "~/.config/google-chrome/Default/Cookies"
    elif browser.lower() == "chromium":
        cookie_file = "~/.config/chromium/Default/Cookies"
    else:
        raise ValueError("Browser must be either Chrome or Chromium.")

    # Set the default linux password
    config = {"my_pass": "peanuts", "iterations": 1, "cookie_file": cookie_file}
    if not collection.is_locked():
        label_to_check = f"{browser.capitalize()} Safe Storage"
        items1 = collection.get_all_items()
        for item in items1:
            if item.get_label() == label_to_check:
                config["my_pass"] = item.get_secret()
    else:
        print("keyring is locked")
        exit(1)
    return config


"""
    # Try to get pass from Gnome / libsecret if it seems available
    # https://github.com/n8henrie/pycookiecheat/issues/12
    try:
        import gi

        gi.require_version("Secret", "1")
        from gi.repository import Secret
    except ImportError:
        pass
    else:
        flags = Secret.ServiceFlags.LOAD_COLLECTIONS
        service = Secret.Service.get_sync(flags)

        gnome_keyring = service.get_collections()
        unlocked_keyrings = service.unlock_sync(gnome_keyring).unlocked

        keyring_name = "{} Safe Storage".format(browser.capitalize())

        for unlocked_keyring in unlocked_keyrings:
            for item in unlocked_keyring.get_items():
                if item.get_label() == keyring_name:
                    item.load_secret_sync()
                    config["my_pass"] = item.get_secret().get_text()
                    break
            else:
                # Inner loop didn't `break`, keep looking
                continue

            # Inner loop did `break`, so `break` outer loop
            break
"""

**Comment by aakhmetz** [comment]
I had the same problem, and solution of munich259272 worked for me

**Comment by rafaelribeiroo** [comment]
> You can close this case.
> I believe i was having problem with importing gi module
> 
> instead i am using `secretstorage` module now and it seems to work for my Linux machine.
> I am not an expert in python but somehow it works now for me with little editing for the get_linux_config
> 
> `
> def get_linux_config(browser: str) -> dict:
> """Get the settings for Chrome/Chromium cookies on Linux.
> 
> ```
> Args:
>     browser: Either "Chrome" or "Chromium"
> Returns:
>     Config dictionary for Chrome/Chromium cookie decryption
> 
> """
> bus = secretstorage.dbus_init()
> collection = secretstorage.get_any_collection(bus)  ## login keyring
> # Verify supported browser, fail early otherwise
> if browser.lower() == "chrome":
>     cookie_file = "~/.config/google-chrome/Default/Cookies"
> elif browser.lower() == "chromium":
>     cookie_file = "~/.config/chromium/Default/Cookies"
> else:
>     raise ValueError("Browser must be either Chrome or Chromium.")
> 
> # Set the default linux password
> config = {"my_pass": "peanuts", "iterations": 1, "cookie_file": cookie_file}
> if not collection.is_locked():
>     label_to_check = f"{browser.capitalize()} Safe Storage"
>     items1 = collection.get_all_items()
>     for item in items1:
>         if item.get_label() == label_to_check:
>             config["my_pass"] = item.get_secret()
> else:
>     print("keyring is locked")
>     exit(1)
> return config
> ```
> 
> `

For me it's returning
`NameError: name 'secretstorage' is not defined
`
Do u know what could be?

**Comment by munish259272** [comment]
you can try installing secret storage

pip install SecretStorage

**Comment by rafaelribeiroo** [comment]
> you can try installing secret storage
> 
> pip install SecretStorage

I already installed

**Comment by n8henrie** [comment]
Make sure you're using the same python that you used to install.

For example, if you use: `/path/to/python -m pip install secretstorage`, then you should be able to import: `/path/to/python -c 'import secretstorage'`

**Comment by brianjmurrell** [comment]
> You can close this case. I believe i was having problem with importing gi module
> 
> instead i am using `secretstorage` module now and it seems to work for my Linux machine. I am not an expert in python but somehow it works now for me with little editing for the get_linux_config
> 
> ` def get_linux_config(browser: str) -> dict: """Get the settings for Chrome/Chromium cookies on Linux.
> 
> ```
> Args:
>     browser: Either "Chrome" or "Chromium"
> Returns:
>     Config dictionary for Chrome/Chromium cookie decryption
> 
> """
> bus = secretstorage.dbus_init()
> collection = secretstorage.get_any_collection(bus)  ## login keyring
> # Verify supported browser, fail early otherwise
> if browser.lower() == "chrome":
>     cookie_file = "~/.config/google-chrome/Default/Cookies"
> elif browser.lower() == "chromium":
>     cookie_file = "~/.config/chromium/Default/Cookies"
> else:
>     raise ValueError("Browser must be either Chrome or Chromium.")
> 
> # Set the default linux password
> config = {"my_pass": "peanuts", "iterations": 1, "cookie_file": cookie_file}
> if not collection.is_locked():
>     label_to_check = f"{browser.capitalize()} Safe Storage"
>     items1 = collection.get_all_items()
>     for item in items1:
>         if item.get_label() == label_to_check:
>             config["my_pass"] = item.get_secret()
> else:
>     print("keyring is locked")
>     exit(1)
> return config
> ```
> 
> `

So with this function, am I supposed to be able to now do:

```python
from pycookiecheat import BrowserType, chrome_cookies
import requests

url = 'https://secure.example.com'

# Uses Chrome's default cookies filepath by default
cookies = chrome_cookies(url)
print(cookies)
r = requests.get(url, cookies=cookies)

# Using an alternate browser
cookies = chrome_cookies(url, password=get_linux_config(browser="chrome")['my_pass'], browser=BrowserType.CHROME)
```

Because with the above I am still seeing:

```
Traceback (most recent call last):
  File "/tmp/cookies", line 53, in <module>
    cookies = chrome_cookies(url)
              ^^^^^^^^^^^^^^^^^^^
  File "/home/brian/.local/lib/python3.12/site-packages/pycookiecheat/chrome.py", line 343, in chrome_cookies
    row["value"] = chrome_decrypt(
                   ^^^^^^^^^^^^^^^
  File "/home/brian/.local/lib/python3.12/site-packages/pycookiecheat/chrome.py", line 91, in chrome_decrypt
    return clean(decrypted)
           ^^^^^^^^^^^^^^^^
  File "/home/brian/.local/lib/python3.12/site-packages/pycookiecheat/chrome.py", line 53, in clean
    return decrypted[:-last].decode("utf8")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcd in position 0: invalid continuation byte
```

**Comment by munish259272** [comment]
Try with firefox

**Comment by n8henrie** [comment]
> So with the above function, am I supposed to be able to now do:

@brianjmurrell No, I don't think that is going to work, each browser backend has its own method of storing the keys and will use its own password. One will often get that error when the password is wrong.
