### ISSUE TITLE
Empty response

### ISSUE THREAD

**Issue by jmspaggi** [n8henrie/pycookiecheat#30]
- **Operating system and version**: Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux
- **Python version**: Python 3.7.6
- **pycookiecheat version**: Dev branch

## My Issue
I'm not sure if I'm doing something wrong or if there is an issue.
first, it says that by default it takes chromium cookies, which is what I want. However I'm getting this error:
```
Unable to connect to cookie_file at: /home/username/.config/google-chrome/Default/Cookies
```
Changing to the correct folder with that command: 
```
cookies = chrome_cookies(url,cookie_file="/home/username/.config/chromium/Default/Cookies")
```
Printing the cookies variable gives me all the correct keys, but all values are empty.

Instead of that, trying to force the browser with this:
```
cookies = chrome_cookies(url, browser="Chromium")
```
Returns the same empty list. Here is the full output:
```
>>> from pycookiecheat import chrome_cookies
>>> url = 'https://domain.com/lel/fr/mes-groupes'
>>> cookies = chrome_cookies(url, browser="Chromium")
>>> print(cookies)
{'registration_origin': '', 'autoexclusion': '', 'pausedejeu': '', '__utma': '', '__utmc': '', '__utmz': '', '_ga': '', '_gid': '', 'AB_precedent': '', 'AB_vu': '', '__errAttempt': '', '__zlcmid': '', 'domain_auth': '', 'domain_login': '', 'logged_in': '', 'typeTestAB': '', 'iam_session_transferred': '', 'lq-test': '', 'urlRedirection': '', 'catfishAfficher': ''}
```

Looking into the SQLite database, they are v11 cookies.

I'm able to get my password using  secret-tool search application chromium but not sure it helps.

## [WHYT](http://mattgemmell.com/what-have-you-tried)

---

Please make sure you've taken these steps before submitting a new issue:

- [ ] Include the Python and pycookiecheat version in your issue
- [ ] Ensure you're running a supported version of Python
- [ ] Run pycookiecheat in debug mode if applicable and include
  relevant output
- [ ] Search the existing (including closed) issues
- [ ] Please use [codeblocks][1] for any code, config, program output, etc.

[1]: https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by jmspaggi** [comment]
Ok.
Passing the password and the browser works well and gives the expected result. I think it's a valid workaround.

"cookies = chrome_cookies(url, browser="Chromium", password="abcdabcdabcdabcdabcdabcd")"

PAssword is retrived with secret-tool search application chromium.

Closing the issue,.

**Comment by n8henrie** [comment]
You're right, it looks like the code path now checks for Chrome before Chromium -- on one hand I'd prefer to switch this back to stay consistent with the docs (and to make the open source project the "easier" path), but on the other hand this might break existing functionality. I will probably just update the docs to note that it looks for Chrome, then Chromium.

I'm not familiar with secret-tool -- thanks for the info.
