### ISSUE TITLE
 cookies expire in day or in random time 

### ISSUE THREAD

**Issue by PraveenPenguin** [n8henrie/pycookiecheat#36]
- **Operating system and version**: Fedora 33
- **Python version**:python 3.7
- **pycookiecheat version**: master branch 

## My Issue
cookies expire in day or in random time 

## [WHYT](http://mattgemmell.com/what-have-you-tried)

---

Please make sure you've taken these steps before submitting a new issue:

- [x] Include the Python and pycookiecheat version in your issue
- [ ] Ensure you're running a supported version of Python
- [ ] Run pycookiecheat in debug mode if applicable and include
  relevant output
- [x] Search the existing (including closed) issues
- [x] Please use [codeblocks][1] for any code, config, program output, etc.

[1]: https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by n8henrie** [comment]
I'm not sure that I understand the question, but I think the answer to this question will vary depending on the specifics of the website and the specific cookie on that website.

In other words, the date that a cookie will expire varies depending on the cookie.
