### ISSUE TITLE
Which is default, Chromium or Chrome?

### ISSUE THREAD

**Issue by velle** [n8henrie/pycookiecheat#45]
![image](https://github.com/n8henrie/pycookiecheat/assets/4488298/719313cf-21ef-4002-a800-9b578d9cf10c)

I believe the answer is Chrome :)

Sincerely.

**Comment by n8henrie** [comment]
You're right, that is confusing. Default is `Chrome`: https://github.com/n8henrie/pycookiecheat/blob/master/src/pycookiecheat/pycookiecheat.py#L228
