### ISSUE TITLE
Warning messages could be very helpful

### ISSUE THREAD

**Issue by velle** [n8henrie/pycookiecheat#46]
Like many others I got the error: "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb9 in position 3: invalid start byte". 

In the very end I had two issues. 1) I had set "Chrome" instead of "Chromium" as the browser. 2) I had not installed "gi". 

But it was only after I spent quite some time looking into your source code and injecting my own print statements that I was able to figure things out :)

In my case it could have looked something like:

    WARNING: Could not import gi. Using keyring as fallback.
    WARNING: Could not find matching key using keyring. Using default Linux secret "peanuts", which works on some setups. 
    ERROR: Decoding with utf-8 of decrypted value failed. This is most likely because the encryption was run with incorrect key. 

Sincerely

**Comment by n8henrie** [comment]
I agree, will work on this. And thank you for your generous donation!

**Comment by n8henrie** [comment]
Sorry this took me so long! The initial implementation is fairly bare-bones but should cover the cases mentioned above without excessive verbosity.

Next I need to make the logging verbosity configurable in the new CLI.
