### ISSUE TITLE
Firefox support wanted?

### ISSUE THREAD

**Issue by grandchild** [n8henrie/pycookiecheat#48]
## My Issue

I'd like to add Firefox support, and want to gauge interest.

## [WHYT](http://mattgemmell.com/what-have-you-tried)

I have implemented a basic Firefox cookie retrieval method that even works while Firefox is running (which has a lock on the `cookies.sqlite` DB).

- Would you be interested in a PR adding this feature?
- If yes, would you prefer I add a new source file (currently it's all one python file)?

**Comment by n8henrie** [comment]
Hi -- I'm traveling so apologies if responses are delayed, and thanks for creating an issue for this.

I'm primarily a Firefox user (created this extension before learning the true gospel of FF haha), so yes I would be happy to have FF support. A PR to this effect would be appreciated!

I would probably refactor into a separate module.

**Comment by grandchild** [comment]
Cool! That's nice to hear, so I'll start working on this.

I'll create a `firefox_cookies()` method that behaves the same as `chrome_cookies()`, to get us started. In a later PR, one could think about such things as "Get a cookie to this website, don't care about the browser, just search all available".

My initial PR will target Linux, I _can_ test on Windows, but I can't really test Mac. But I guess in the end it's all about the canonical paths.

**Comment by n8henrie** [comment]
Sounds great. I can test on Linux and Mac. I don't support windows, as I don't have any windows devices and don't know it well.

**Comment by grandchild** [comment]
I finally got it to a reviewable state 😄  -- The code itself was done in hours, but the unit tests gave me some grief. But it's all working now 🎉

More in the PR...

**Comment by grandchild** [comment]
#50 is merged.
