### ISSUE TITLE
is there a reason for cryptography 3.4.6 and not 41.0.3 ?

### ISSUE THREAD

**Issue by fire17** [n8henrie/pycookiecheat#56]
Check out  #53  [Bump cryptography from 3.4.6 to 41.0.3](https://github.com/n8henrie/pycookiecheat/pull/53)

is there a specific reason its 3.4.6 and not the bumped?

hackers hacking hackers?.. hope not
all the best!

**Comment by n8henrie** [comment]
Sorry, it was on the dev branch. Now pushed to master. Thanks for the issue!

**Comment by fire17** [comment]
For sure :)
Awesome project!
Did you find something similar on windows?
Thanks and all the best ! @n8henrie

**Comment by n8henrie** [comment]
Sorry, I'm not much of a windows user, so I am not sure of a windows alternative.

I imagine you could use pycookiecheat within windows subsystem for linux though. If you try that, could you report back?

**Comment by fire17** [comment]
I didn't find the problem being with the dependencies, but opening the cookies file.. SQLite didn't load it. Could try from wsl2 why not..
If this will work cross platform it could be amazing!
I'm building dynamic UIs that present data from various platforms that the user is already using. & This would be amazing to not have them sign in again (on a specialized browser) for all their accounts. Instead it would just be seamless

**Comment by n8henrie** [comment]
Sounds very interesting! If you make progress on pycookiecheat support in windows via WSL please report back :)
