### ISSUE TITLE
Consider using rookie as cookies extractor

### ISSUE THREAD

**Issue by thewh1teagle** [n8henrie/pycookiecheat#58]
I made this library called `rookiepy` which available in `pypi`
https://github.com/thewh1teagle/rookie
You can use it to extract the sessions from many browsers on many platforms

**Comment by n8henrie** [comment]
Thanks for providing an alternative -- I love me some rust!

Closing as this isn't exactly a pycookiecheat issue.

**Comment by grandchild** [comment]
I opened a proper issue https://github.com/thewh1teagle/rookie/issues/18
