### ISSUE TITLE
Doesn't return session cookies

### ISSUE THREAD

**Issue by brianjmurrell** [n8henrie/pycookiecheat#71]
- **Operating system and version**: Fedora 40
- **Python version**: 3.12.6
- **pycookiecheat version**: __version__ = "v0.7.0"

## My Issue
One particular cookie being set is not being returned by `chrome_cookies()`

I have the following code:

```python
            cookies = chrome_cookies(f"https://secure.[redacted].com", browser=BrowserType.CHROMIUM)
            for cookie in cookies.keys():
                print(f"Found cookie {cookie} = {cookies[cookie]} for secure.example.com")
```
but it is failing to return the `session-id` cookie which you can see is being set by the website in this devtools response:

![image](https://github.com/user-attachments/assets/016dd5f9-5178-4b0b-9683-681057ea311e)

Additionally, in devtools->Application tab we can see the cookie is present for the site:

![image](https://github.com/user-attachments/assets/09fca67e-2d93-4c52-974e-fdd359184caf)

`pycookiecheat` doesn't return that cookie either but it returns a dozen or so others.

## [WHYT](https://web.archive.org/web/20140712194323/http://mattgemmell.com/what-have-you-tried/)

I don't know what to try other than the above code snippet and `pycookiecheat` CLI.

---

Please make sure you've taken these steps before submitting a new issue:

- [x] Include the Python and pycookiecheat version in your issue
- [x] Ensure you're running a supported version of Python
- [x] Run pycookiecheat in debug mode if applicable and include
  relevant output
  - Tried with half-a-dozen `-v` flags but didn't get any kind of debug output and `--help` doesn't detail any other kind of debug/verbose options
- [x] Search the existing (including closed) issues
  - Tried, but not entirely sure what to search for though.
- [x] Please use [codeblocks][1] for any code, config, program output, etc.

[1]: https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by n8henrie** [comment]
That's a session cookie. Because session cookies don't persist beyond a session, I presume they never leave your browser's memory and are never written to disk, which means they won't be retrievable by this tool (or likely any other tool that can't read your browser's memory). If you need access to these, I suggest you look into browser extensions instead of command-line tools.

**Comment by brianjmurrell** [comment]
Yet another attempt at trying to get data from this particular website failed. :frowning_face:

> I suggest you look into browser extensions instead of command-line tools

Fair enough.  Any suggestions?  I'd want to write the cookies (or even just the page content) out on every page refresh (I also employ a timed-page reloader).

Quite honestly, I'd prefer (and did attempt) to just log into the website using Python requests (like I do for a number of others) but this particular website has that Akamai Bot Detector garbage in front of it so I need the browser to establish the session and use an extension to reload the page I want to keep the session alive.  And as I said, I'd be just as happy to have the page written to a file on page reload even.

**Comment by n8henrie** [comment]
> Any suggestions?

Nothing terribly specific, but if you're familiar with JavaScript, you might be able to work something out with GreaseMonkey / TamperMonkey (I'm no good at JS though, so this could be a dead end).

For similar tasks I've used [playwright](https://playwright.dev/python/) in the past. If you haven't tried it, it's worth a look.
