### ISSUE TITLE
sqlite3.OperationalError into UnicodeDecodeError | Chrome Update

### ISSUE THREAD

**Issue by crachefeu** [n8henrie/pycookiecheat#72]
- **Operating system and version**: MacOS Sonoma 14.2.2
- **Python version**: 3.12.2
- **pycookiecheat version**: 0.7.0
- **Chrome Version**: 130.0.6723.70

## My Issue

I don't track Google Chrome updates as they happen, but I am fairly certain Chrome updated it self on my machine yesterday evening. When trying to use `chrome_cookies(domain)` sqlite3 now fails to decode the `encrypted_value` column:

```
130.0.6723.7sqlite3.OperationalError: Could not decode to UTF-8 column 'encrypted_value' with text 'v10�z���Y ��Jf��j�~%
                                                                                                            ��!�Q���*G�I�
c9�9�w/we�Sk�H1���e�J������U�T�;�s]��o3����8����7*��J���G���l����'
```

## [WHYT](https://web.archive.org/web/20140712194323/http://mattgemmell.com/what-have-you-tried/)

I have a feeling this may be linked to the Chrome update as things were working fine yesterday, so I tried clearing cookies for a specific domain and then connecting to that service to generate a new set of cookies. This appears to resolve the sqlite3 error but then leads into a UnicodeDecodeError:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "xxxx/.venv/lib/python3.12/site-packages/pycookiecheat/chrome.py", line 346, in chrome_cookies
    row["value"] = chrome_decrypt(
                   ^^^^^^^^^^^^^^^
  File "xxxx/.venv/lib/python3.12/site-packages/pycookiecheat/chrome.py", line 93, in chrome_decrypt
    return clean(decrypted)
           ^^^^^^^^^^^^^^^^
  File "xxxx/.venv/lib/python3.12/site-packages/pycookiecheat/chrome.py", line 55, in clean
    return decrypted[:-last].decode("utf8")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xda in position 0: invalid continuation byte
```

The fact that clearing the cookies and regenerating a new set changes the error seems to indicate this might have something to do with Chrome?

I'm not excluding that something else may have changed on my system, but based on the above do you have any ideas about may be the issue?

Thanks for your help !

---

Please make sure you've taken these steps before submitting a new issue:

- [x] Include the Python and pycookiecheat version in your issue
- [x] Ensure you're running a supported version of Python
- [x] Run pycookiecheat in debug mode if applicable and include
  relevant output
- [x] Search the existing (including closed) issues
- [x] Please use [codeblocks][1] for any code, config, program output, etc.

[1]: https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by chrisgavin** [comment]
I've also just started hitting this issue. Indeed clearing cookies got around the first error and now I'm hitting the second one you describe.

If I inspect the decrypted value, I can see that the decryption is actually happening correctly, it's just there's 32 bytes of extra data at the start. It does seem likely that this is caused by a change in Chromium somewhere.

**Comment by crachefeu** [comment]
@chrisgavin could this be why the first problem is happening?
```
Tests are added to verify the migration, as well as verify that
if the domain is modified, the cookie is no longer considered
valid, and will not load into the cookie store. An additional
test is added to verify that encrypted data without a hash
is handled correctly.
```
https://chromium-review.googlesource.com/c/chromium/src/+/5792044

If I understand correctly, it is saying that once you've migrated, cookies that don't have the domain aren't loaded ? i.e. it might load gibberish which is undecodable ?

**Comment by chrisgavin** [comment]
The first problem seems to come from not even being able to read the value out of the database due to the SQLite client expecting it to be a UTF-8 string. I suspect the proper fix for that is changing the text factory the SQL client uses to be bytes, but I have not had time to investigate that yet.

**Comment by n8henrie** [comment]
Wow, this is awesome, big thanks to both of you! And great detective work, thank you for linking to the source above.

(I have a big exam in 6 days and hopefully will be sticking to the books this week if my response times are slow.)

**Comment by BABYSHARPYIN** [comment]
I hope you get a good grade.

**Comment by n8henrie** [comment]
Thanks :)

**Comment by mgedmin** [comment]
Thank you all, the hints in this thread helped me get my VPN login script working again.  Here's the exact patch I'm using:

```diff
diff --git a/src/pycookiecheat/chrome.py b/src/pycookiecheat/chrome.py
index 2ecee56..0dc5bf9 100644
--- a/src/pycookiecheat/chrome.py
+++ b/src/pycookiecheat/chrome.py
@@ -49,11 +49,17 @@ def clean(decrypted: bytes) -> str:
         decrypted, stripped of padding
     """
     last = decrypted[-1]
-    if isinstance(last, int):
+    if not isinstance(last, int):
+        last = ord(last)
+
+    try:
         return decrypted[:-last].decode("utf8")
+    except UnicodeDecodeError:
+        pass
 
+    # v24 prepends a SHA256 hash in front of the value
     try:
-        cleaned = decrypted[: -ord(last)].decode("utf8")
+        return decrypted[32:-last].decode("utf8")
     except UnicodeDecodeError:
         logging.error(
             "UTF8 decoding of the decrypted cookie failed. This is most often "
@@ -62,8 +68,6 @@ def clean(decrypted: bytes) -> str:
         )
         raise
 
-    return cleaned
-
 
 def chrome_decrypt(
     encrypted_value: bytes, key: bytes, init_vector: bytes
@@ -309,6 +313,8 @@ def chrome_cookies(
         raise e
 
     conn.row_factory = sqlite3.Row
+    # encrypted cookies are binary data and cannot be decoded to UTF-8
+    conn.text_factory = lambda data: str(data, encoding="latin1")
 
     # Check whether the column name is `secure` or `is_secure`
     secure_column_name = "is_secure"
```
