### ISSUE TITLE
pycookiecheat not working on Chrome 130

### ISSUE THREAD

**Issue by Shimada666** [n8henrie/pycookiecheat#76]
- **Operating system and version**: Macos 14.7
- **Python version**: 3.11
- **pycookiecheat version**:  0.7.0

## My Issue
Hi! I recently found that pycookiecheat is not working properly and throws the following exception:
```
➜  jq-notebook git:(master) ✗ pycookiecheat -v -v -v -v -v -v -u https://google.com -b Chrome
DEBUG:keyring.backend:Loading KWallet
DEBUG:keyring.backend:Loading SecretService
DEBUG:keyring.backend:Loading Windows
DEBUG:keyring.backend:Loading chainer
DEBUG:keyring.backend:Loading libsecret
DEBUG:keyring.backend:Loading macOS
b'c\\\xef\xf6\xf6b\xc7\xc6\xf9\x88\x97\\[\xb0\xc9?!\xc1\x1e\x84\x0c\x9av"\x81\x9bY\x0e\xcbM\xa3q49C382A82DF387414CE3007A99DEF08A:FG=1'
Traceback (most recent call last):
  File "/opt/homebrew/bin/pycookiecheat", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pycookiecheat/__main__.py", line 53, in main
    cookies = chrome_cookies(
              ^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pycookiecheat/chrome.py", line 344, in chrome_cookies
    row["value"] = chrome_decrypt(
                   ^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pycookiecheat/chrome.py", line 92, in chrome_decrypt
    return clean(decrypted)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pycookiecheat/chrome.py", line 54, in clean
    return decrypted[:-last].decode("utf8")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xef in position 2: invalid continuation byte
```

I suspect it might be related to the Chrome version, so I installed Chrome 129, and it works fine.
```
 ➜  jq-notebook git:(master) ✗ pycookiecheat -v -v -v -v -v -v -u https://google.com -b Chrome
DEBUG:keyring.backend:Loading KWallet
DEBUG:keyring.backend:Loading SecretService
DEBUG:keyring.backend:Loading Windows
DEBUG:keyring.backend:Loading chainer
DEBUG:keyring.backend:Loading libsecret
DEBUG:keyring.backend:Loading macOS
b'AVYB7cpM1ez0NX5TjwVkMoR8EEl5IVWmr780DV*********'
b'BcC3JtSuxU3kIPPF/AAMdM6*********'
b'AEesaJPHscoB*********'
...

```

Could you please take a look?

## [WHYT](https://web.archive.org/web/20140712194323/http://mattgemmell.com/what-have-you-tried/)

---

Please make sure you've taken these steps before submitting a new issue:

- [ ] Include the Python and pycookiecheat version in your issue
- [ ] Ensure you're running a supported version of Python
- [ ] Run pycookiecheat in debug mode if applicable and include
  relevant output
- [ ] Search the existing (including closed) issues
- [ ] Please use [codeblocks][1] for any code, config, program output, etc.

[1]: https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by n8henrie** [comment]
Please try master -- a recent change in how chrome stores cookies

**Comment by n8henrie** [comment]
v0.8.0 was just released and may fix this -- please give it a shot and report back.

**Comment by Shimada666** [comment]
@n8henrie 
Thanks! Now It works fine!

**Comment by n8henrie** [comment]
Glad to hear it!
