### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 0: invalid continuation byte

### ISSUE THREAD

**Issue by oliverhuynh** [n8henrie/pycookiecheat#77]
- **Operating system and version**: Ubuntu 20.04.6 LTS (Focal Fossa)
- **Python version**: Python 3.8.10
- **pycookiecheat version**: 0.8.0 (built from lastest master)

## My Issue
I meet the following issue after upgrade Chrome to Google Chrome 131.0.6778.69. Can someone help or give me some hints to fix this?

```
(.venv) [saas]oliver@oliver-HP-Laptop-15-dy2xxx:~/localprojects/pycookiecheat$ python -m  pycookiecheat  -v -v -v -v -v -v  https://github.com
INFO:pycookiecheat.chrome:Was not able to import `Secret` from `gi.repository`
DEBUG:keyring.backend:Loading KWallet
DEBUG:keyring.backend:Loading SecretService
DEBUG:keyring.backend:Loading Windows
DEBUG:keyring.backend:Loading chainer
DEBUG:keyring.backend:Loading libsecret
DEBUG:keyring.backend:Loading macOS
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/oliver/localprojects/pycookiecheat/src/pycookiecheat/__main__.py", line 70, in <module>
    main()
  File "/home/oliver/localprojects/pycookiecheat/src/pycookiecheat/__main__.py", line 59, in main
    cookies = get_cookies(
  File "/home/oliver/localprojects/pycookiecheat/src/pycookiecheat/common.py", line 192, in get_cookies
    cookies = pycookiecheat.chrome_cookies(
  File "/home/oliver/localprojects/pycookiecheat/src/pycookiecheat/chrome.py", line 361, in chrome_cookies
    row["value"] = chrome_decrypt(
  File "/home/oliver/localprojects/pycookiecheat/src/pycookiecheat/chrome.py", line 98, in chrome_decrypt
    return clean(decrypted)
  File "/home/oliver/localprojects/pycookiecheat/src/pycookiecheat/chrome.py", line 51, in clean
    return decrypted[:-last].decode("utf8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 0: invalid continuation byte

```

## [WHYT](https://web.archive.org/web/20140712194323/http://mattgemmell.com/what-have-you-tried/)
I did check a similar ticket but I'm not using chromium
 - [Ticket ](https://github.com/n8henrie/pycookiecheat/issues/70)

---

Please make sure you've taken these steps before submitting a new issue:

- [x] Include the Python and pycookiecheat version in your issue
- [x] Ensure you're running a supported version of Python
- [x] Run pycookiecheat in debug mode if applicable and include
  relevant output
- [x] Search the existing (including closed) issues
- [x] Please use [codeblocks][1] for any code, config, program output, etc.

[1]: https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by varenc** [comment]
Same.  Recent Chrome update broke pycookiecheat as far as I can tell.

**Comment by n8henrie** [comment]
Sorry this took so long to get back to you.

pycookiecheat is working on Chrome 131.0.6778.205 for MacOS.

This specific error is *usually* due to a problem getting the correct password to decrypt your cookies file.

I assume you're using Gnome?

**Comment by n8henrie** [comment]
Have you been through https://github.com/n8henrie/pycookiecheat?tab=readme-ov-file#installation-notes-regarding-alternative-keyrings-on-linux ?

**Comment by varenc** [comment]
My issue is resolved! Sorry for adding noise and confusion. My error was actually different. It did appear right after a Chrome update but the root cause was that I was on v0.7.0 not v0.8.0.  Upgrading fixed it.  But issue is different than @oliverhuynh's.
