### ISSUE TITLE
Expedia post request to get hotel list

### ISSUE THREAD

**Issue by vijay-axis** [n8henrie/pycookiecheat#9]
I am trying to get list of hotels for a particular location in expedia. But i get a 400 bad request. Although i am able to make request from Chromium console i am getting 400 bad request when a make it from scrapy.

import scrapy
import pdb
from scrapy.http.cookies import CookieJar
from pycookiecheat import chrome_cookies

class ExpediaHotelSpider(scrapy.Spider):
    """Expedia spider"""
    name = "expediaspider"
    allowed_domains = ["expedia.co.in"]
    start_urls = ["https://www.expedia.co.in/Hotel-Search"]

    def parse(self, response):
        cookies = chrome_cookies('https://www.expedia.co.in/Hotel-Search')
        request = scrapy.FormRequest(url='https://www.expedia.co.in/Hotel-Search?inpAjax=true&responsive=true&origin=HOT:SR:UpdateSearch',
                    cookies=cookies,
                    formdata={  'adults': '1',
                                'destination': 'Bengaluru (and vicinity), India',
                                'endDate': '16/02/2016',
                                'startDate': '15/02/2016',
                                'sort': 'recommended',
                                'regionId':'6053307',
                                'hashParam':'2035b06478adf2e9364eb7ce702f5d86ac136201'
                                }, method='POST',
                    callback='parse_1')
        return [request]

    def parse_1(self, response):
        pdb.set_trace()

**Comment by n8henrie** [comment]
Sorry it's taken me a minute to respond.

I don't know whether or not this is in keeping with the Expedia terms of service, so I suggest you investigate to make sure. I'll keep my response more general.

I don't know much about scapy, as I try to avoid libraries that don't support python3 (although it looks like there are a few forks with compatibility).

The first step would be to ensure whether or not `pycookiecheat` is returning the correct cookies or not. I have just visited the Expedia URL you listed above, and running `pycookiecheat.chrome_cookies()` on the URL seems to properly return the cookies for me. If it's also returning cookies for you, I don't think this is an issue with `pycookiecheat`, but perhaps with the way you're trying to use scapy (is ajax an issue?), or the way that scapy expects the cookies.

Can you verify whether `pycookiecheat` is returning the cookies?

**Comment by vijay-axis** [comment]
Sorry the issue was not with pycookiecheat. They issue was with hashParam in the the post request. Any way thank you for reply.
